#!/usr/bin/env python3

import os.path
import sys
import subprocess
import shutil

script_file = os.path.realpath(__file__)
scripts_dir = os.path.dirname(script_file)

is_help = False
command_index = 1

if sys.argv[1] == 'help':
	command_index = 2
	is_help = True

command = sys.argv[command_index]
argv = sys.argv[command_index + 1:]
if argv and argv[len(argv) - 1] == '.':
	argv = argv[:-1]
	os.environ['DEPO_CWD'] = os.getcwd()
script = os.path.join(scripts_dir, "_" + command + ".py")

if is_help:
	subprocess.run([sys.executable, script, '-h'], check=True)
	sys.exit(0)

if sys.platform == 'win32':
	repo = [shutil.which('repo')]
else:
	repo = ['repo']
subprocess.run(repo + ['forall', '-c', sys.executable, script] + argv, check=True)
